---
resources:
   - name: source-code
     type: git
     icon: github
     source:
        uri: https://github.com/DipayanP007/Jenkins-Concourse-maven-project.git
        branch: master
        username: ((user))
        password: ((pw))
   

jobs:
   - name: clean-test
     plan:
        - get: source-code
          trigger: true
        - task: maven-exec
          config:
             platform: linux
             image_resource:
                 type: docker-image
                 source:
                    repository: maven
             
             inputs:
                - name: source-code
             run:
                path: source-code/ci/script.sh

   - name: package-artifact
     build_log_retention:
        builds: 5
        minimum_succeeded_builds: 2
     plan:
          - get: source-code
            passed: [clean-test]
            trigger: true
          - task: package
            config:
               platform: linux
               image_resource:
                  type: docker-image
                  source: {repository: maven}

               inputs:
                  - name: source-code
               caches:
               - path: /root/.m2/repository

               outputs:
               - name: target
                 path: source-code/target

               run:
                  path: source-code/ci/task-script.sh
            

          - task: find-all
            config:
               platform: linux
               image_resource:
                  type: docker-image
                  source: {repository: openjdk}
               
               inputs:
                  - name: target

               caches:
                  - path: /root/.m2/repository
               run:
                  path: java
                  args:
                    - -jar 
                    - target/sample-application-for-jenkins-1.0-SNAPSHOT.jar